# -*- mode: sh; coding: utf-8 -*-

##################################################
### キーバインド
## Emacsキーバインド
bindkey -e

## ^ で上位ディレクトリへ移動
## 入力の途中では通常の文字入力として扱う
function cdup-or-insert-circumflex() {
  if [[ -z "$BUFFER" ]]; then
    echo
    cd ..
    zle reset-prompt
  else
    zle self-insert '^'
  fi
}
zle -N cdup-or-insert-circumflex
bindkey '\^' cdup-or-insert-circumflex

## M-^ で git のワークツリーのトップに移動
function cd-git-toplevel() {
  local toplevel
  if toplevel=$(git rev-parse --show-toplevel 2> /dev/null); then
    echo
    cd $toplevel
    zle reset-prompt
  fi
}
zle -N cd-git-toplevel
bindkey '^[\^' cd-git-toplevel

## コマンドの入力中にC-pで、その入力で履歴を検索する
autoload history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey "^P" history-beginning-search-backward-end
bindkey "^N" history-beginning-search-forward-end

## C-w は リージョンが有効なときは kill-region にする
## backward-kill-word は `/' と `=' で止まるように
function backward-kill-word-non-greedy {
  WORDCHARS='*?_-.[]~&;!#$%^(){}<>' zle backward-kill-word
}

function kill-region-or-backward-kill-word-non-greedy {
  if ((REGION_ACTIVE)); then
    zle kill-region
  else
    backward-kill-word-non-greedy
  fi
}

zle -N kill-region-or-backward-kill-word-non-greedy
bindkey '^W' kill-region-or-backward-kill-word-non-greedy

## 元の動作は C-x C-w で
bindkey "^X^W" backward-kill-word


## コマンドラインスタックで、退避したコマンドを表示
function push-line-with-buffer-stack {
  POSTDISPLAY="
stack: $LBUFFER"
  zle push-line
}
zle -N push-line-with-buffer-stack
bindkey "^[q" push-line-with-buffer-stack


## Enter で ls と git status を表示する
function do_enter() {
  if [ -n "$BUFFER" ]; then
    zle accept-line
    return 0
  fi
  echo
  eval ls # alias を展開したい
  if [ "$(git rev-parse --is-inside-work-tree 2> /dev/null)" = 'true' ]; then
    echo
    echo -e "\e[0;33m--- git status ---\e[0m"
    git status -sb
  fi
  zle reset-prompt
  return 0
}
zle -N do_enter
bindkey '^m' do_enter

## Alt+Enter で git diff を表示する
function my-git-diff {
  git diff
  zle reset-prompt
  return 0
}
zle -N my-git-diff
bindkey "^[^m" my-git-diff

##################################################
### ヒストリ
## メモリ上のヒストリ数
export HISTSIZE=2000000

## ファイルに保存するヒストリ数とそのファイル
export SAVEHIST=$HISTSIZE
export HISTFILE=~/var/log/zsh-history

## ヒストリファイルにコマンドラインだけでなく実行時刻と実行時間も保存する
setopt extended_history

## 同じコマンドラインを連続で実行した場合はヒストリに登録しない
setopt hist_ignore_dups

## スペースで始まるコマンドラインはヒストリに登録しない
setopt hist_ignore_space

## ヒストリから冗長なスペースを削除する
setopt hist_reduce_blanks

## zshプロセス間でヒストリを共有する
setopt share_history

## すぐヒストリファイルに追記する
setopt inc_append_history

## C-sでのヒストリ検索が潰されてしまうため、出力停止・開始用にC-s/C-qを使わない
setopt no_flow_control

## 全てのヒストリを表示
function history-all { history -E 1 }



##################################################
### プロンプト
## PROMPT内で変数展開・コマンド置換・算術演算を実行する
setopt prompt_subst

## 色の簡易表記のため
autoload -U colors
colors

## バージョン管理システムの状態を表示する
## 詳細は man zshcontrib
autoload -Uz add-zsh-hook
function _setup_vcs_info {
  autoload -Uz vcs_info
  zstyle ':vcs_info:*' max-exports 3
  # formats は `hg:default' のように表示される。編集されているかどうかによって、`hg' の部分の色が変わる。
  # get-revision が true だと %b が長くなるので、__branch-name__ と書いておいて後から置換する。
  # %c stagedstr
  # %u unstagedstr
  # %s 使っている VCS
  # %b ブランチ名
  # %r リポジトリ名
  # %a アクション名
  zstyle ':vcs_info:*' actionformats '%F{white}%c%u%s%f%F{white}:%f%F{green}__branch-name__%f:%F{magenta}%a%f%c%u' '%b' '%r'
  zstyle ':vcs_info:*' formats       '%F{white}%c%u%s%f%F{white}:%f%F{green}__branch-name__%f' '%b' '%r'
  zstyle ':vcs_info:*' enable git hg

  local check_for_changes_enabled=1
  if [[ check_for_changes_enabled -eq 1 ]]; then
    zstyle ':vcs_info:*' check-for-changes true
    zstyle ':vcs_info:hg:*' get-revision true # hg で check-for-changes を有効にするには
    zstyle ':vcs_info:hg:*' use-simple false  # この2つの設定が必要
  else
    zstyle ':vcs_info:*' check-for-changes false
    zstyle ':vcs_info:hg:*' get-revision false
    zstyle ':vcs_info:hg:*' use-simple true # hexdump がないと速くならない。Cygwin では util-linux パッケージにある。
  fi

  zstyle ':vcs_info:git:*' stagedstr "%F{136}"
  zstyle ':vcs_info:git:*' unstagedstr "%F{63}"
  zstyle ':vcs_info:hg:*' unstagedstr "%F{136}"

  function _update_vcs_info_message {
    vcs_info
    # get-revision が true だと %b が長いブランチ名になるので、短くしている
    vcs_info_msg_0_=${vcs_info_msg_0_//__branch-name__/${vcs_info_msg_1_%%:*}}
  }

  function enable_vcs_info {
    add-zsh-hook precmd _update_vcs_info_message
  }
  function disable_vcs_info {
    add-zsh-hook -d precmd _update_vcs_info_message
  }

  if [[ $ENABLE_VCS_INFO -eq 1 ]]; then
    enable_vcs_info
  fi
}

autoload -Uz is-at-least
if is-at-least 4.3.10; then
  _setup_vcs_info
fi


function setup_prompt {
  local prompt_color
  local prompt_body
  local prompt_mark prompt_mark_normal prompt_mark_error

  if [ -z "$SSH_CONNECTION" ]; then
    prompt_body=''
    prompt_color=cyan
  else
    prompt_body="%n@${EC2_INSTANCE_NAME:-%m}"
    if [ "$EC2_INSTANCE_ENV" = "production" ]; then
      prompt_color=magenta
    else
      prompt_color=yellow
    fi
  fi

  case "$TERM" in
    dumb*|emacs*)
      PROMPT='%m%# '
      RPROMPT=''
      ;;
    *)
      PROMPT="%F{$prompt_color}${PROMPT_BODY:-$prompt_body}%f\${prompt_mark_color}\${prompt_mark}%f "
      local rprompt
      rprompt=(
        "%F{$prompt_color}["
        "\${vcs_info_msg_0_:+\${vcs_info_msg_0_} }%f" # VCS の情報があれば表示
        "%F{$prompt_color}"
        # $PWD は ~ が展開されているので ~ に戻し、リポジトリ名の部分に下線を付ける。
        # リポジトリ名は $vcs_info_msg_2_ に入っている。
        "\${\${\${PWD/#\$HOME/~}/\/\${vcs_info_msg_2_}\///%U\${vcs_info_msg_2_}%u/}/%\/\${vcs_info_msg_2_}//%U\${vcs_info_msg_2_}%u}"
        " %*]%f"
      )
      RPROMPT=${(j..)rprompt}

      ## コマンドの終了ステータスに応じてプロンプトの色を変える。
      ## 一度色違いで表示したら、プロンプト再描画の際には色を戻す。
      function setup_prompt_mark_color {
        if (( prompt_mark_displayed != 1 && $? != 0 )); then
          prompt_mark_color='%F{magenta}'
          prompt_mark="🐙"
        else
          prompt_mark_color=''
          prompt_mark="🐳"
        fi
        prompt_mark_displayed=1
      }
      add-zsh-hook precmd setup_prompt_mark_color

      function reset_prompt_mark_displayed {
        prompt_mark_displayed=0
      }
      add-zsh-hook preexec reset_prompt_mark_displayed
      ;;
  esac
}
setup_prompt



##################################################
### 補完
## 初期化
autoload -U compinit
compinit -u

## 補完リストに色をつける
if type dircolors > /dev/null; then
  eval `dircolors -b` # LS_COLORSの設定
  zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
else
  zstyle ':completion:*:default' list-colors 'di=34;01' 'ln=35' 'so=32' 'ex=31' 'bd=46;34' 'cd=43;34'
fi
zstyle ':completion:*:*:*:*:processes' list-colors "=(#b)[^0-9]#([0-9]#)*[0-9:.]## ([^ ]#)*=$color[none]=$color[bold];$color[cyan]=$color[green]"

## 補完リストを全てグループ分けして表示
zstyle ':completion:*' group-name ''

## 補完リストが1画面に収まらなかったときのプロンプト
zstyle ':completion:*' list-prompt '%SAt %p: Hit TAB for more, or the character to insert%s'

## 補完リストで候補のカーソル選択を有効に
zstyle ':completion:*:default' menu select=1

## カーソル選択で候補を選んでいるときのプロンプト（補完リストが1画面に収まらなかった場合）
zstyle ':completion:*' select-prompt '%SScrolling active: current selection at %p%s'

## m:{a-z}={A-Z}: 小文字を大文字に変えたものでも補完する
#zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

## 補完候補をキャッシュする。
zstyle ':completion:*' use-cache yes

## 詳細な情報を使う
zstyle ':completion:*' verbose yes

## メッセージフォーマット
zstyle ':completion:*:descriptions' format '%B%d%b' # 補完リストの上に出てくるdescription
zstyle ':completion:*:messages' format '%d' # 補完時のメッセージ
zstyle ':completion:*:warnings' format 'No matches for: %d' # 補完がマッチしなかったとき

## man の補完をセクションごとに区分する
zstyle ':completion:*:manuals' separate-sections true

## セクション番号を挿入する(セクション1以外)
zstyle ':completion:*:manuals.(^1*)' insert-sections true

## コマンドラインに既に入力されているものは補完対象にしない
zstyle ':completion:*:(rm|mv|cp|diff|kill):*' ignore-line other

## parent: foo/../ から foo を補完しない
## pwd: ../ からカレントディレクトリを補完しない
zstyle ':completion:*:(cd|mv|cp):*' ignore-parents parent pwd

## 辞書順ではなく数字順に並べる
setopt numeric_glob_sort

## 補完リストを詰めて表示
setopt list_packed

## ディレクトリの補完に続いてデリミタ等を入力したとき、
## ディレクトリ末尾の「/」を自動的に削除する
setopt auto_remove_slash



##################################################
### 展開
## --prefix=~/localというように「=」の後でもファイル名展開を行う
setopt magic_equal_subst

## 拡張globを有効にする
setopt extended_glob

## 展開後のパスがディレクトリだったら最後に「/」をつける
#setopt mark_dirs

## {a-c}をa b cに展開する
setopt brace_ccl



##################################################
### ジョブ
## jobsでプロセスIDも出力する
setopt long_list_jobs

## 実行したプロセスの消費時間が3秒以上かかったら
## 自動的に消費時間の統計情報を表示する。
REPORTTIME=3



##################################################
### エイリアス
alias mv='nocorrect mv'

case "$OSTYPE" in
  freebsd*)
    alias ls='ls -F -G -w'
    export LSCOLORS=ExgxfxdxCxDxDxhbadacec
    ;;
  *)
    alias ls='ls -F --color=auto --show-control-chars'
    export TIME_STYLE=long-iso
    ;;
esac

alias ll='ls -l'
alias la='ls -a'

alias be='bundle exec'


function bundle-cd {
  local output exit_status
  output=`bundle show $1`
  exit_status=$?
  if [ $exit_status -eq 0 ]; then
    cd "$output"
  else
    echo $output 1>&2
    return $exit_status
  fi
}


function man {
  # mb: blinking
  # md: bold
  # so: standout-mode
  # us: underline
  env \
    LESS_TERMCAP_mb=$'\E[01;31m' \
    LESS_TERMCAP_md=$'\E[01;38;5;76m' \
    LESS_TERMCAP_so=$'\E[48;5;94;1;37m' \
    LESS_TERMCAP_us=$'\E[04;38;5;146m' \
    LESS_TERMCAP_me=$'\E[0m' \
    LESS_TERMCAP_se=$'\E[0m' \
    LESS_TERMCAP_ue=$'\E[0m' \
    man "$@"
}

function list-colors-display {
  print -n "normal colors\t"
  echo 'e.g. \\e[30m ... \\e[0m'
  for i in {30..37}; do
    printf "\e[%d;m %3d \e[0m" i i
  done

  print -n "\nlight colors\t"
  echo 'e.g. \\e[1;30m ... \\e[0m'
  for i in {30..37}; do
    printf "\e[1;%d;m %3d \e[0m" i i
  done

  print -n "\n256 colors\t"
  echo 'e.g. 128 -> \\e[38;5;128m ... \\e[0m'
  for i in {0..255}; do
    printf "\e[38;5;%dm %3d \e[0m" i i
    (( ($i + 1) % 16 )) || echo
  done
}

## grep
typeset -a grep_options
grep_help=$(grep --help)

# バイナリファイルにはマッチさせない。
grep_options=(--binary-files=without-match )

# 管理用ディレクトリを無視する
if echo $grep_help | grep -q -- --exclude-dir
then
  for ext (.svn .git .hg .deps .libs)
  do
    grep_options=($grep_options --exclude-dir=${ext})
  done
fi

# 可能なら色を付ける。
if echo $grep_help | grep -q -- --color
then
  grep_options=($grep_options --color=auto)
fi

# ディレクトリは再帰的にgrepする
#grep_options=($grep_options --recursive)

alias grep="grep $grep_options"
unset grep_help


##################################################
### ディレクトリスタック
## cdしたとき、移動前のディレクトリを自動でpushdする
setopt auto_pushd

## pushdのディレクトリスタックに重複を含めない
setopt pushd_ignore_dups


### fzf
## Auto-completion
[[ $- == *i* ]] && source "/opt/homebrew/opt/fzf/shell/completion.zsh" 2> /dev/null

## Key bindings
source "/opt/homebrew/opt/fzf/shell/key-bindings.zsh"
bindkey "^O" fzf-file-widget
export FZF_DEFAULT_COMMAND='unset REPORTTIME && rg --color=never --files --no-ignore --hidden --no-messages'
export FZF_DEFAULT_OPTS='--height 40% --border'
export FZF_CTRL_T_COMMAND="${FZF_DEFAULT_COMMAND}"
export FZF_CTRL_R_OPTS='--bind=ctrl-e:accept'


### gitワークツリー内に移動したときはブランチ名を表示
function chpwd_show_git_branch() {
  local git_toplevel
  git_toplevel=$(git rev-parse --show-toplevel 2> /dev/null)

  # 移動先がgitワークツリー内で、移動前と別ワークツリーだったら
  if [[ -n $git_toplevel && $git_toplevel != $git_toplevel_prev ]]; then
    echo "## ${fg[green]}$(git rev-parse --abbrev-ref @)"
  fi

  git_toplevel_prev=${git_toplevel}
}
add-zsh-hook chpwd chpwd_show_git_branch

### ビルトインコマンドでも run-help を使えるようにする
unalias run-help > /dev/null 2>&1 && autoload -Uz run-help


### URL の入力をエスケープする
autoload -Uz url-quote-magic
zle -N self-insert url-quote-magic


### パッケージ管理
PACKAGE_BASE_DIR="$ZDOTDIR/packages"
source $ZDOTDIR/package.zsh
source $ZDOTDIR/package-conf/zsh-manydots-magic.zsh
source $ZDOTDIR/package-conf/zsh-git-escape-magic.zsh
#source $ZDOTDIR/package-conf/zsh-syntax-highlighting.zsh
#source $ZDOTDIR/package-conf/z.zsh


### ホストごとの設定を読む
source_if_exist "${HOME}/.zsh.d/zshrc-${HOST}"
source_if_exist "${HOME}/.zsh.d/zshrc.local"


### ホームディレクトリから開始
cd
